# Generated by Django 4.1.6 on 2023-02-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полная имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/authors/', verbose_name='Изображение')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Об автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='books.author', verbose_name='Авторы'),
        ),
    ]
